In [1]:
import numpy as np

In [3]:
#Creating a 1 Dimensional Array
x = np.array([1, 2, 3, 4, 5])
y = np.array([9, 10])

print(x)
print('The shape of X is ', x.shape)

print(y)
print('The shape of Y is ', y.shape)


[1 2 3 4 5]
The shape of X is  (5,)
[ 9 10]
The shape of Y is  (2,)


In [4]:
#Creating a 2D dimensional Array

z = np.array([
    [1, 2], [3, 4]
])

print(z)
print('The shape of Z is ', z.shape)

[[1 2]
 [3 4]]
The shape of Z is  (2, 2)


In [8]:
#Creating a multi-dimensional Array

w = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

print(w)
print('The shape of W is ', w.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
The shape of W is  (3, 3, 3)


In [9]:
#Numpy Functions

#Arange
A10 = np.arange(30)
A10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
#Reshape
B10 = A10.reshape(-1, 3)
B10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [18]:
#Zeros
np_zeros = np.zeros((2,3))
np_zeros

np_zeros.astype(int)

array([[0, 0, 0],
       [0, 0, 0]])

In [21]:
#Ones
np_ones = np.ones((3, 5))
np_ones
np_ones.astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
#Full
np_full = np.full((5, 3), 5)
np_full

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [27]:
#eye
np_eye = np.eye(6, 5)
np_eye
np_eye.astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [33]:
#Linspace 
np_linspace = np.linspace(0, 97, num=2)
np_linspace
np_linspace.astype(int)

array([ 0, 97])

In [35]:
#Random

np_rand = np.random.random_sample((2,3))
print('Randaom Sample ', np_rand)

np_rand_two = np.random.rand(2, 3)
print('Random number ', np_rand_two)


Randaom Sample  [[0.51320731 0.01593708 0.5695448 ]
 [0.19902643 0.51679965 0.72499197]]
Random number  [[0.39246687 0.44630854 0.62498112]
 [0.99474661 0.0450724  0.41142086]]


In [38]:
#Accessing Elements of Numpy Array

print(z)

print(z[1, 0])

[[1 2]
 [3 4]]
3
